name: Caller

on:
  workflow_dispatch:

jobs:
  llamar-workflow:
      #- name: Checkout
      #  uses: actions/checkout@v4
      uses: ValentinGarciaIriart/GH_Actions/.github/workflows/ogWorkflow.yaml@main
      with:
        saludo: "Hola amigos soy mickey mouse!"