name: Intento Artifact

on:
  workflow_dispatch:

jobs:
  crear-artifact:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: echo Mi nombre es Valentin > archivo.txt
      - run: echo Y estoy preparando una entrevista >> archivo.txt
      - name: Generar Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mensaje
          path: archivo.txt
  consumir-artifact:
    needs: crear-artifact
    runs-on: "ubuntu-latest"
    steps:
      - name: Descargar Artifact
        uses: actions/download-artifact@v4
        with:
          name: mensaje
      - name: Imprimir contenido
        run: cat archivo.txt
