name: ejEntrevista

on:
  push: 
    branches: ["main"]
    paths: 
      - "*/src/**"

jobs:
  build-and-deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Repo
          uses: actions/checkout@v4
        - name: Setup Node
          uses: actions/setup-node@v4
          with:
           node-version: '20'
        - name: Install Dependencies
          run: npm Install
        - name: Node Test
          run: npm test

#Esto lo que hace es el checkout del repo, usa la acción de node para instalar dependencias y realizar test, en realidad no hay un proyecto como tal