name: final-callable

on:
  workflow_call:
    inputs:
      invocacion:
        type: string
        required: true
      buleano:
        type: boolean
        required: true

jobs:
  calleo:
    runs-on: "ubuntu-latest"
    steps:
    - run: echo "El string que pasas es ${{ inputs.invocacion }} y el booleano es ${{ inputs.buleano }}"