name: build-and-push-ghcr

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18, 20]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build

      - name: Archive build output
        if: success()
        run: zip -r dist.zip dist

      - name: Upload artifact
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: dist-${{ matrix.node }}
          path: dist.zip

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/my-app:node${{ matrix.node }} .
          docker push ghcr.io/${{ github.repository }}/my-app:node${{ matrix.node }}
