name: ejMatrix

on: 
  push:
    branches: ["main"]


jobs:
  use-matrix:
    strategy:
      matrix:
        os: ["ubuntu-latest","macos-latest","windows-latest"]
        python-version: ["3.8", "3.10"]
    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
         python-version:  ${{ matrix.python-version }}
      - run: pip install -r requirements
      - run: pytest