name: Secretos y +

on:
  push:
    branches: ["main"]

jobs:
  uso-secret:
    runs-on: "ubuntu-latest"
    steps:
      - name: Printear Secretos
        run: echo "El secreto que tengo guardado es ${{ secrets.PASSWDGH }}"
  caller-job:
    uses: ValentinGarciaIriart/GH_Actions/.github/workflows/ogWorkflow.yaml@main
    with:
      saludo: "Hola me llamo valen jijo"

